In [12]:
import gymnasium as gym
import mazegym  # noqa: F401  # Registers MazeGym environments.

import numpy as np
import matplotlib.pyplot as plt
import time
import random

env = gym.make("Maze5x5Fixed-v0")

print(env.reset())

action = 0
print(env.step(action))

time.sleep(5)
env.render()

(array([[1, 1, 1, 1, 1],
       [1, 2, 0, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 0, 3, 1],
       [1, 1, 1, 1, 1]], dtype=int8), {'valid_moves': [1]})
(array([[1, 1, 1, 1, 1],
       [1, 2, 0, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 0, 3, 1],
       [1, 1, 1, 1, 1]], dtype=int8), -2, False, False, {'valid_moves': [1]})


array([[1, 1, 1, 1, 1],
       [1, 2, 0, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 0, 3, 1],
       [1, 1, 1, 1, 1]], dtype=int8)