In [1]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/ivanosipov/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100.0%


In [2]:
prediction = model(data) # forward pass

In [5]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [6]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [7]:
optim.step() #gradient descent

In [13]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

tensor([ 8., 27.], grad_fn=<PowBackward0>)


In [14]:
Q = 3*a**3 - b**2

tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [15]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [16]:
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
